import { Link } from "wouter";
import { ArrowUpRight, ArrowRight, Github, Mail, Layers, Database, FileSpreadsheet, Sun, Moon } from "lucide-react";
import portrait from "../../../../attached_assets/tayyab-hero.png";
import { projects, type Project } from "@/data/projects";
import { useTheme } from "@/hooks/useTheme";
import "@/portfolio.css";

export function SiteHeader() {
  const { theme, cycle } = useTheme();
  return <header className="site-header"><div className="shell header-inner">
    <Link href="/" className="wordmark" aria-label="Tayyab, home">tayyab<span>.</span></Link>
    <nav aria-label="Main navigation"><a href="/#work">Work</a><a href="/#about">About</a><Link href="/play">Play <span aria-hidden="true">↗</span></Link><a className="nav-contact" href="/#contact">Let’s talk</a>
    <button className="theme-switch" onClick={cycle} aria-label={`Theme: ${theme}. Change theme`}>{theme === "dark" ? <Moon size={17}/> : <Sun size={17}/>}</button></nav>
  </div></header>;
}
export function SiteFooter() {
  return <footer className="shell site-footer"><span>© {new Date().getFullYear()} Tayyab Naveed Akhtar</span><span>Built with curiosity. Based in Pakistan.</span><a href="https://github.com/tayyab602" target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={14}/></a></footer>;
}
export function ProjectVisual({ project }: { project: Project }) {
  if (project.image) return <div className={`project-visual ${project.tone}`}><div className="browser-frame"><div className="browser-bar"><i/><i/><i/><span>{project.live ? new URL(project.live).hostname : "Tic Tac Toe Pro / Flutter"}</span></div><img src={`${import.meta.env.BASE_URL}projects/${project.image}`} alt={`${project.name} project preview`} loading="lazy" width="1440" height="1000"/></div></div>;
  if (project.slug === "inventory") return <div className="project-visual sand"><div className="inventory-diagram"><span className="eyebrow">APPLICATION AT A GLANCE</span><h3>From stock.<br/>To insight.</h3><div className="system-flow"><span><Layers/>Inventory</span><b aria-hidden="true">→</b><span><Database/>MySQL</span><b aria-hidden="true">→</b><span><FileSpreadsheet/>Reports</span></div><p>Java desktop application · MySQL database</p></div></div>;
  if (project.slug === "tictactoe") return <div className="project-visual orange"><div className="mini-board" aria-hidden="true">{["X","O","","","X","O","","","X"].map((v,i)=><span key={i} className={v === "X" ? "cross" : ""}>{v}</span>)}</div><span className="visual-caption">YOUR NEXT MOVE?</span></div>;
  return <div className="project-visual lilac"><div className="numzoo-art"><span className="eyebrow">ANDROID GAME</span><strong>Numzoo<span>↗</span></strong><div className="number-tiles" aria-hidden="true"><i>01</i><i>02</i><i>03</i></div><p>Mobile development, with a playful side.</p></div></div>;
}
export default function PortfolioHome() {
  return <div className="portfolio"><a className="skip-link" href="#main">Skip to content</a><SiteHeader/><main id="main">
    <section className="shell intro"><div className="intro-copy"><p className="eyebrow"><span className="status-dot"/> DEVELOPER · CS STUDENT · BUILDER</p><h1>I build things<br/>people can <em>use.</em></h1><p className="intro-description">I’m Tayyab. I build websites, desktop software, and mobile games—learning full-stack development by making things for real people.</p><div className="button-row"><a className="button primary" href="#work">Explore my work <ArrowRight size={18}/></a><a className="text-link" href="#contact">Let’s build something <ArrowUpRight size={17}/></a></div><div className="intro-meta"><span>Air University, Kamra</span><span>AUCIS Vice President</span></div></div><div className="portrait-panel"><span className="portrait-greeting" lang="ur">سلام</span><img src={portrait} alt="Tayyab Naveed Akhtar" fetchPriority="high"/><div className="portrait-note"><span>A LITTLE ABOUT ME</span><strong>Code. Community.<br/>A bit of competition.</strong></div><span className="portrait-coordinate">SKP → KAMRA, PK</span></div></section>
    <div className="shell discipline-strip"><span>Web experiences</span><span>Desktop applications</span><span>Mobile games</span><span>Always learning <ArrowUpRight size={16}/></span></div>
    <section className="shell section" id="work"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Less talk.<br/>More things built.</h2></div><p>From campus communities to business workflows.<br/>A closer look at what I’ve been making.</p></div><div className="featured-grid">{projects.slice(0,3).map((p,i)=><article key={p.slug} className={`work-card ${i === 0 ? "lead-project" : ""}`}><Link href={`/projects/${p.slug}`} className="visual-link" aria-label={`Explore ${p.name}`}><ProjectVisual project={p}/></Link><div className="project-copy"><p className="eyebrow">0{i+1} / {p.category}</p><h3><Link href={`/projects/${p.slug}`}>{p.name}</Link></h3><p>{p.summary}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="project-actions"><Link className="text-link" href={`/projects/${p.slug}`}>View project <ArrowRight size={16}/></Link>{p.live && <a href={p.live} target="_blank" rel="noopener noreferrer" className="text-link muted-link">Live website <ArrowUpRight size={16}/></a>}</div></div></article>)}</div>
    <div className="games-heading"><h3>A playful side, too.</h3><span>Mobile projects & interactive experiments</span></div><div className="games-grid">{projects.slice(3).map(p=><article className="work-card" key={p.slug}><Link href={`/projects/${p.slug}`} className="visual-link" aria-label={`Explore ${p.name}`}><ProjectVisual project={p}/></Link><div className="project-copy"><p className="eyebrow">{p.category}</p><h3>{p.name}</h3><p>{p.summary}</p><Link className="text-link" href={p.slug === "tictactoe" ? "/play" : `/projects/${p.slug}`}>{p.slug === "tictactoe" ? "Play the browser edition" : "View project"}<ArrowUpRight size={16}/></Link></div></article>)}</div>
    <details className="more-work"><summary>More from the workshop <span>Earlier projects ↗</span></summary><div>{[["Flutter Learn AI","AI tutor, flashcards & quizzes","flutter-learn-ai"],["Brainy Bingo","C++ learning game","BRAINYBINGO"],["Mobile Learning AI Tool","Flutter learning application","Mobile-Learning-AI-Tool"]].map(([name,desc,repo])=><a key={repo} href={`https://github.com/tayyab602/${repo}`} target="_blank" rel="noopener noreferrer"><strong>{name}</strong><span>{desc}</span><ArrowUpRight size={18}/></a>)}</div></details></section>
    <section className="play-invitation"><div className="shell"><p className="eyebrow">A SHORT BREAK FROM SCROLLING</p><h2>Think you can<br/>outplay the <em>AI?</em></h2><p>Five rounds. Three difficulties. Your next move could earn a spot on the board.</p><Link href="/play" className="button primary">Take the challenge <ArrowUpRight size={18}/></Link><div className="invitation-marks" aria-hidden="true">× ○</div></div></section>
    <section className="shell section about-section" id="about"><div><p className="eyebrow">02 / THE PERSON BEHIND THE CODE</p><h2>Learning by doing.<br/>Building with purpose.</h2></div><div className="about-copy"><p>I’m a Computer Science student at <strong>Air University AAC, Kamra</strong>. I started coding in Fall 2024 and have been expanding my toolkit through projects ever since.</p><p>As <strong>Vice President of AUCIS</strong>, I get to contribute to a community beyond the classroom. Building our recruitment website brought those two parts of my life together.</p><p>I also run a WhatsApp-based beauty store. Managing products and customers has given me a practical appreciation for software that makes everyday work easier.</p><a className="text-link" href="https://www.linkedin.com/in/tayyab-naveed-akhtar-922721313/" target="_blank" rel="noopener noreferrer">More about my journey <ArrowUpRight size={17}/></a></div></section>
    <section className="shell skills-section" id="skills"><div className="section-heading"><div><p className="eyebrow">03 / MY TOOLKIT</p><h2>Skills put to work.</h2></div><p>Currently deepening HTML, CSS, JavaScript,<br/>and Node.js through full-stack development.</p></div><div className="skill-grid">{[["Web development","HTML · CSS · JavaScript · Node.js","My current focus, alongside society websites and client work."],["Apps & games","Java · C# · Flutter · Dart","Desktop applications, Android projects, and game logic."],["Data & tools","MySQL · MongoDB · Firebase · Git","Persistent data, version control, and the tools behind the interface."]].map(([title,stack,desc],i)=><div key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><strong>{stack}</strong><p>{desc}</p></div>)}</div></section>
    <section className="shell section contact-section" id="contact"><p className="eyebrow">HAVE SOMETHING IN MIND?</p><h2>Let’s make<br/>something <em>useful.</em></h2><a className="contact-email" href="mailto:tayyabnaveed13@gmail.com">tayyabnaveed13@gmail.com <ArrowUpRight/></a><div className="button-row"><a className="text-link" href="https://github.com/tayyab602" target="_blank" rel="noopener noreferrer"><Github size={17}/>GitHub</a><a className="text-link" href="mailto:tayyabnaveed13@gmail.com"><Mail size={17}/>Email me</a></div></section>
    </main><SiteFooter/></div>;
}
